MwangiBlogApp/Controllers/BlogPostsController.cs
using MwangiBlogApp.Helpers;
using MwangiBlogApp.Models;
using PagedList;
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MwangiBlogApp.Controllers

{
    [Authorize]
    //[Authorize(Roles = "Admin, Moderator")]

    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        // GET: BlogPosts
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.SearCh = searchStr;

            var blogList = IndexSearch(searchStr);

            int pageSize = 9;
            int pageNumber = page ?? 1;
          
            return View(blogList.ToPagedList(pageNumber, pageSize));
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;

            if (searchStr != null)
            {
                result = db.BlogPosts.AsQueryable();
                result = result.Where(p => p.Title.Contains(searchStr)
                || p.Body.Contains(searchStr)
                || p.Comments.Any(c => c.Body.Contains(searchStr)
                || c.Author.FirstName.Contains(searchStr)
                || c.Author.LastName.Contains(searchStr)
                || c.Author.DisplayName.Contains(searchStr)
                || c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.BlogPosts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(p => p.Slug == Slug);

            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Abstract,Body,MediaUrl,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                /*instance of class StringUtilities which only has a function  that takes the
                 argument of title from the blogpost instance and passes that value to var Slug
                 variable("which is not yet set
                */
                var Slug = StringUtilities.URLFriendly(blogPost.Title);

                //this line checks if the string is NULL or no value was entered in the input box
                //and throws a custome error
                if (string.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                             
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaUrl = "/Uploads/" + fileName;
                }
                //I go out to the database and check to see if there are any other slugs that looks
                //identical basically checks for uniqueness in the database
                //and throw out a custom error
                if (db.BlogPosts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                //set the value to the variable you declared in 
                //var Slug = StringUtilities.URLFriendly(blogPost.Title);
                blogPost.Slug = Slug;
                blogPost.Created = DateTimeOffset.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include ="Id,Title,Abstract,slug,Body,MediaUrl,Published,Created,Updated")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var newSlug = StringUtilities.URLFriendly(blogPost.Title);
                if(newSlug != blogPost.Slug)
                {
                    if (string.IsNullOrEmpty(newSlug))
                    {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(blogPost);
                    }

                    if (db.BlogPosts.Any(p => p.Slug == newSlug))
                    {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(blogPost);
                    }

                    blogPost.Slug = newSlug;
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaUrl = "/Uploads/" + fileName;
                }

                blogPost.Updated = DateTimeOffset.Now;

                db.Entry(blogPost).State = EntityState.Modified;

                //db.BlogPosts.Add(blogPost); Code that caused my program not to edit changes
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

MwangiBlogApp/Controllers/HomeController.cs
using MwangiBlogApp.Models;
using System;
using System.Configuration;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;

namespace MwangiBlogApp.Controllers
{
    [Authorize]
    //[RequireHttps]
    //[Authorize(Roles = "Admin, Moderator")]
    public class HomeController : Controller

    {
        private ApplicationDbContext context = new ApplicationDbContext();
        //Allows this controller to access the database 
        private ApplicationDbContext db = new ApplicationDbContext();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Contact(EmailModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var body = "<p>Email From: <bold>{0}</bold>({1})</p><p>Message:</p><p>{2}</p>";

                    var from = model.FromEmail + "<" + WebConfigurationManager.AppSettings["emailto"] + ">";

                    //model.Body = "This is a message from your Blog site. The name and email of the contacting person is above";

                    var email = new MailMessage(from, ConfigurationManager.AppSettings["emailto"])
                    {
                        Subject = "Blog Contact Email",

                        Body = string.Format(body, model.FromName, model.FromEmail, model.Body),

                        IsBodyHtml = true
                    };

                    var svc = new PersonalEmail();
                    await svc.SendAsync(email);

                    return View(new EmailModel());
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    await Task.FromResult(0);
                }
            }
            return View(model);
        }


        //[Authorize(Roles = " Admin, Moderator")]

        public ActionResult Index()
        {
            return View();

        }



        private object SearchUtility(/*object p*/)
        {
            throw new NotImplementedException();
        }

        private object Take(int v)
        {
            throw new NotImplementedException();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Mbutha application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            EmailModel model = new EmailModel();
            return View(model);
        }
    }
}

MwangiBlogApp/Views/Home/About.cshtml
<div class="row entries-wrap wide">
    <div class="entries">
        <hr />    
        <section class="s-content s-content--top-padding s-content--narrow">

            <div class="row narrow">
                <div class="col-full s-content__main">
                    <h3 class="display-1 display-1--with-line-sep">The MosBlog All about Full Stack. </h3>
                    <p>
                        Budding Full Stack developer who enjoys all things tech. Currently building Web sites and web applications using HTML5, CSS3, Javascripts, Bootstrap and Microsoft SQL and employing Azure for deployment
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-full s-content__main">
                    <p>
                        <img src="images/thumbs/about/about-1000.jpg"
                             srcset="images/thumbs/about/about-2000.jpg 2000w,
                             images/thumbs/about/about-1000.jpg 1000w,
                             images/thumbs/about/about-500.jpg 500w"
                             sizes="(max-width: 2000px) 100vw, 2000px" alt="">
                    </p>

                    <h2>This Is Our Story</h2>

                    <p>
                       Ive worked as Professional Satelite installer for Directv and At&t, Worked for NCR and ICON staffing as a Customer Engineer and now pursuing a career in Full Stack web development.

                    <p>
                        Second generation immigrant from Kenya and enjoying myself growing a young family in Durham NC
                    </p>

                    <hr>

                    @*<div class="row block-1-2 block-tab-full">
                        <div class="col-block">
                            <h4 class="quarter-top-margin">Who We Are.</h4>
                            <p>Lorem ipsum Nisi amet fugiat eiusmod et aliqua ad qui ut nisi Ut aute anim mollit fugiat qui sit ex occaecat et eu mollit nisi pariatur fugiat deserunt dolor veniam reprehenderit aliquip magna nisi consequat aliqua veniam in aute ullamco Duis laborum ad non pariatur sit.</p>
                        </div>

                        <div class="col-block">
                            <h4 class="quarter-top-margin">Our Mission.</h4>
                            <p>Lorem ipsum Nisi amet fugiat eiusmod et aliqua ad qui ut nisi Ut aute anim mollit fugiat qui sit ex occaecat et eu mollit nisi pariatur fugiat deserunt dolor veniam reprehenderit aliquip magna nisi consequat aliqua veniam in aute ullamco Duis laborum ad non pariatur sit.</p>
                        </div>

                        <div class="col-block">
                            <h4 class="quarter-top-margin">Our Vision.</h4>
                            <p>Lorem ipsum Nisi amet fugiat eiusmod et aliqua ad qui ut nisi Ut aute anim mollit fugiat qui sit ex occaecat et eu mollit nisi pariatur fugiat deserunt dolor veniam reprehenderit aliquip magna nisi consequat aliqua veniam in aute ullamco Duis laborum ad non pariatur sit.</p>
                        </div>

                        <div class="col-block">
                            <h4 class="quarter-top-margin">Our Core Values.</h4>
                            <p>Lorem ipsum Nisi amet fugiat eiusmod et aliqua ad qui ut nisi Ut aute anim mollit fugiat qui sit ex occaecat et eu mollit nisi pariatur fugiat deserunt dolor veniam reprehenderit aliquip magna nisi consequat aliqua veniam in aute ullamco Duis laborum ad non pariatur sit.</p>
                        </div>

                    </div>*@

                </div> <!-- s-content__main -->
            </div> 
        </section> <!-- end s-content -->

    </div> <!-- item-entry -->
</div> <!-- end entries -->

MwangiBlogApp/Views/Home/Contact.cshtml
@model MwangiBlogApp.Models.EmailModel

<!-- s-content
    ================================================== -->
<section class="s-content s-content s-content--narrow">
    <div class="row">
        <div class="row">
            <div class="col-six tab-full">
                <h4>Where to Find Me</h4>
                <address>
                    Moses Mbutha Mwangi<br />
                    <abbr title="My Physical Address in Durham">P A:</abbr>
                    3612 Weatherby Dr<br />
                    <abbr title="My personal Telephone number">P:</abbr>
                    919.491.1432
                </address>
            </div>
            <div class="col-six tab-full">
                <h4>Contact Info</h4>
                <p>
                    <address>
                        <strong>Support:</strong>   <a href="mosesmwangi1979@gmail.com">mosesmwangi1979@gmail.com</a><br />
                        <strong>Marketing:</strong> <a href="venzauber@gmail.com">venzauber@gmail.com</a>
                    </address>
                </p>
            </div>
        </div>
    <hr />
        <div id="respond" class="col-full">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <fieldset>
                    @Html.TextBoxFor(m => m.FromName, new { @class = "form-control full-width" ,placeholder="PLease enter your full name Your Name*"})
                    @Html.ValidationMessageFor(m => m.FromName)

                    @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control full-width", placeholder = "Please enter your email: example@email.com" })
                    @Html.ValidationMessageFor(m => m.FromEmail)

                    @Html.TextBoxFor(m => m.Subject, new { @class = "form-control full-width", placeholder = "Please type in the subject of your post" })
                    @Html.ValidationMessageFor(m => m.Subject)

                    <span>Type in you comment below</span>

                    @Html.TextBoxFor(m => m.Body, htmlAttributes: new { @id = "editor", @class = "form-control" })
                    <br />
                    <div class="form-field">
                        <button type="submit" class="submit btn btn--primary btn--large full-width">Send Message</button>
                    </div>
                </fieldset>
            }
        </div>
    </div><!-- s-content__main -->
</section> <!-- end s-content -->

@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script src="~/Scripts/tinymce/jquery.tinymce.min.js"></script>
    <script type="text/javascript">
        $(function () {
            tinymce.init({ selector: '#editor' });
        });
    </script>

} 

MwangiBlogApp/Views/Home/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<MwangiBlogApp.Models.BlogPost>
                
<!-- s-content-->

    <section class="s-content">
        <div class="">
            <div class="">
                <img src="images/thumbs/single/standard/standard-1000.jpg"
                     srcset="/images/thumbs/single/standard/standard-2000.jpg 2000w,
                                 /images/thumbs/single/standard/standard-1000.jpg 1000w,
                                 /images/thumbs/single/standard/standard-500.jpg 500w"
                     sizes="(max-width: 2000px) 100vw, 2000px" alt="">
            </div>
        </div>
        <div class="row">
            @*<div class="col-sm-3">
                @using (Html.BeginForm("Index", "BlogPosts", FormMethod.Get, htmlAttributes: new { @class = "form" }))
                {
                    <div class="controls controls-row search-row">
                        <input id="searchStr" name="searchStr" class="form" type="text" placeholder="Search">
                        <button id="searchStr" name="searchStr" class="btn" type="submit">
                            <bu class="icon-search"></bu>
                        </button>
                    </div>
                }
            </div>*@
        </div>
        <div class="row">
            You have Succesfully logged in
        </div>
        

                                </section> <!-- end s-content -->
<!-- s-extra
================================================== -->